string (TIMESTAMP ODBCOMPILER_BUILD_TIME UTC)

macro (write_header)
    file(WRITE ${OUTPUT_FILE}
        "// BuildInfoGenerated.hpp generated by CMake. Changes will be lost! */\n"
        "#define ODBCOMPILER_BUILD_TIME \"${ODBCOMPILER_BUILD_TIME}\"\n")
endmacro ()

# If ODBCOMPILER_UPDATE_BUILDINFO option setting is false, only write a new header
# file but don't replace an existing one
if (NOT ODBCOMPILER_UPDATE_BUILDINFO)
    if (NOT EXISTS ${OUTPUT_FILE})
        write_header()
    endif ()
else ()
    write_header()
endif ()
